services:
  api_gateway:
    build:
      context: .
      dockerfile: api_gateway/Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - service_users
      - service_orders
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      USER_SERVICE_URL: http://service_users:3001
      ORDER_SERVICE_URL: http://service_orders:3002
      API_GATEWAY_PORT: 3000
    env_file:
      - ./docker/dev/api_gateway.env
    networks:
      - platform

  service_users:
    build:
      context: .
      dockerfile: service_users/Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      USER_SERVICE_PORT: 3001
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL:-admin@example.com}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD:-Admin1234!}
      DEFAULT_ADMIN_NAME: ${DEFAULT_ADMIN_NAME:-Project Admin}
    env_file:
      - ./docker/dev/service_users.env
    networks:
      - platform

  service_orders:
    build:
      context: .
      dockerfile: service_orders/Dockerfile
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: development
      LOG_LEVEL: debug
      JWT_SECRET: ${JWT_SECRET:-dev-secret}
      ORDER_SERVICE_PORT: 3002
    env_file:
      - ./docker/dev/service_orders.env
    networks:
      - platform

networks:
  platform:
    driver: bridge

